import mutations from './mutations.js'
import getters from './getters.js'
import actions from './actions.js'

export default {
    namespaced: true,
    state() {
        return {
            blogs: [
                {
                    id: 1,
                    foodImage: new URL("@/assets/blogImages/img--2.png", import.meta.url).href,
                    humanFace: new URL("@/assets/uiFaces/img_2.jpg", import.meta.url).href,
                    foodName: "Margherita Pizza",
                    desc: "Classic Neapolitan pizza topped with fresh tomatoes, mozzarella cheese, and basil leaves.",
                    name: "Jane Doe",
                    date: "5 January 2022",
                },
                {
                    id: 2,
                    foodImage: new URL("@/assets/blogImages/img--3.png", import.meta.url).href,
                    humanFace: new URL("@/assets/uiFaces/img_3.jpg", import.meta.url).href,
                    foodName: "Chicken Biryani",
                    desc: "A flavorful Indian rice dish cooked with marinated chicken, aromatic spices, and saffron.",
                    name: "John Smith",
                    date: "20 February 2022",
                },
                {
                    id: 3,
                    foodImage: new URL("@/assets/blogImages/img--4.png", import.meta.url).href,
                    humanFace: new URL("@/assets/uiFaces/img_4.jpg", import.meta.url).href,
                    foodName: "Sushi Platter",
                    desc: "An assortment of sushi rolls and nigiri made with vinegared rice, seafood, and vegetables.",
                    name: "Alice Johnson",
                    date: "3 March 2022",
                },
                {
                    id: 4,
                    foodImage: new URL("@/assets/blogImages/img--5.png", import.meta.url).href,
                    humanFace: new URL("@/assets/uiFaces/img_5.jpg", import.meta.url).href,
                    foodName: "Avocado Toast",
                    desc: "Toasted sourdough bread topped with smashed avocado, chili flakes, and a drizzle of olive oil.",
                    name: "Robert Brown",
                    date: "17 April 2022",
                },
                {
                    id: 5,
                    foodImage: new URL("@/assets/blogImages/img--6.png", import.meta.url).href,
                    humanFace: new URL("@/assets/uiFaces/img_6.jpg", import.meta.url).href,
                    foodName: "Ramen Bowl",
                    desc: "Japanese noodle soup with a rich broth, tender pork, soft-boiled egg, and fresh vegetables.",
                    name: "Emily Davis",
                    date: "25 May 2022",
                },
                {
                    id: 6,
                    foodImage: new URL("@/assets/blogImages/img--1.png", import.meta.url).href,
                    humanFace: new URL("@/assets/uiFaces/img_1.jpg", import.meta.url).href,
                    foodName: "Spaghetti Carbonara",
                    desc: "A creamy pasta dish made with eggs, cheese, pancetta, and pepper, originating from Rome, Italy.",
                    name: "Lroem Ipsum",
                    date: "12 November 2021",
                },
                {
                    id: 7,
                    foodImage: new URL("@/assets/blogImages/img--2.png", import.meta.url).href,
                    humanFace: new URL("@/assets/uiFaces/img_2.jpg", import.meta.url).href,
                    foodName: "Grilled Cheese",
                    desc: "A golden, crispy sandwich filled with melted cheddar cheese.",
                    name: "Kevin Stone",
                    date: "3 June 2022",
                },
                {
                    id: 8,
                    foodImage: new URL("@/assets/blogImages/img--3.png", import.meta.url).href,
                    humanFace: new URL("@/assets/uiFaces/img_3.jpg", import.meta.url).href,
                    foodName: "Caesar Salad",
                    desc: "Fresh romaine lettuce tossed with Caesar dressing, croutons, and parmesan.",
                    name: "Sarah Lee",
                    date: "14 June 2022",
                },
                {
                    id: 9,
                    foodImage: new URL("@/assets/blogImages/img--4.png", import.meta.url).href,
                    humanFace: new URL("@/assets/uiFaces/img_4.jpg", import.meta.url).href,
                    foodName: "Tacos Al Pastor",
                    desc: "Mexican tacos filled with marinated pork, pineapple, and onions.",
                    name: "Carlos Diaz",
                    date: "21 June 2022",
                },
                {
                    id: 10,
                    foodImage: new URL("@/assets/blogImages/img--5.png", import.meta.url).href,
                    humanFace: new URL("@/assets/uiFaces/img_5.jpg", import.meta.url).href,
                    foodName: "Pancake Stack",
                    desc: "Fluffy pancakes served with maple syrup and berries.",
                    name: "Tina Moore",
                    date: "2 July 2022",
                },
                {
                    id: 11,
                    foodImage: new URL("@/assets/blogImages/img--6.png", import.meta.url).href,
                    humanFace: new URL("@/assets/uiFaces/img_6.jpg", import.meta.url).href,
                    foodName: "Pho Noodle Soup",
                    desc: "Vietnamese noodle soup with beef, herbs, and rice noodles.",
                    name: "Minh Tran",
                    date: "11 July 2022",
                },
                {
                    id: 12,
                    foodImage: new URL("@/assets/blogImages/img--1.png", import.meta.url).href,
                    humanFace: new URL("@/assets/uiFaces/img_1.jpg", import.meta.url).href,
                    foodName: "BBQ Ribs",
                    desc: "Slow-cooked pork ribs glazed with a tangy barbecue sauce.",
                    name: "Frank Turner",
                    date: "19 July 2022",
                },
                {
                    id: 13,
                    foodImage: new URL("@/assets/blogImages/img--2.png", import.meta.url).href,
                    humanFace: new URL("@/assets/uiFaces/img_2.jpg", import.meta.url).href,
                    foodName: "Greek Gyro",
                    desc: "Pita bread filled with spiced meat, tzatziki, tomatoes, and onions.",
                    name: "Elena Petrova",
                    date: "27 July 2022",
                },
                {
                    id: 14,
                    foodImage: new URL("@/assets/blogImages/img--3.png", import.meta.url).href,
                    humanFace: new URL("@/assets/uiFaces/img_3.jpg", import.meta.url).href,
                    foodName: "Croissant",
                    desc: "Flaky, buttery French pastry best served warm.",
                    name: "Marie Dupont",
                    date: "2 August 2022",
                },
                {
                    id: 15,
                    foodImage: new URL("@/assets/blogImages/img--4.png", import.meta.url).href,
                    humanFace: new URL("@/assets/uiFaces/img_4.jpg", import.meta.url).href,
                    foodName: "Pad Thai",
                    desc: "Thai stir-fried noodles with shrimp, peanuts, and lime.",
                    name: "Somsak Pranee",
                    date: "10 August 2022",
                },
                {
                    id: 16,
                    foodImage: new URL("@/assets/blogImages/img--5.png", import.meta.url).href,
                    humanFace: new URL("@/assets/uiFaces/img_5.jpg", import.meta.url).href,
                    foodName: "Cheeseburger",
                    desc: "Juicy beef patty with cheese, lettuce, and tomato in a toasted bun.",
                    name: "Mark Wilson",
                    date: "18 August 2022",
                },
                {
                    id: 17,
                    foodImage: new URL("@/assets/blogImages/img--6.png", import.meta.url).href,
                    humanFace: new URL("@/assets/uiFaces/img_6.jpg", import.meta.url).href,
                    foodName: "Miso Soup",
                    desc: "Japanese soup with tofu, seaweed, and miso paste.",
                    name: "Yuki Tanaka",
                    date: "26 August 2022",
                },
                {
                    id: 18,
                    foodImage: new URL("@/assets/blogImages/img--1.png", import.meta.url).href,
                    humanFace: new URL("@/assets/uiFaces/img_1.jpg", import.meta.url).href,
                    foodName: "Beef Tacos",
                    desc: "Crunchy shells filled with seasoned beef and toppings.",
                    name: "Linda Scott",
                    date: "1 September 2022",
                },
                {
                    id: 19,
                    foodImage: new URL("@/assets/blogImages/img--2.png", import.meta.url).href,
                    humanFace: new URL("@/assets/uiFaces/img_2.jpg", import.meta.url).href,
                    foodName: "Veggie Wrap",
                    desc: "Whole wheat wrap filled with grilled veggies and hummus.",
                    name: "Jordan Green",
                    date: "9 September 2022",
                },
                {
                    id: 20,
                    foodImage: new URL("@/assets/blogImages/img--3.png", import.meta.url).href,
                    humanFace: new URL("@/assets/uiFaces/img_3.jpg", import.meta.url).href,
                    foodName: "Fried Chicken",
                    desc: "Crispy, golden chicken served with mashed potatoes.",
                    name: "Angela Price",
                    date: "15 September 2022",
                },
                {
                    id: 21,
                    foodImage: new URL("@/assets/blogImages/img--4.png", import.meta.url).href,
                    humanFace: new URL("@/assets/uiFaces/img_4.jpg", import.meta.url).href,
                    foodName: "Chocolate Cake",
                    desc: "Moist chocolate cake topped with ganache and sprinkles.",
                    name: "Laura Hill",
                    date: "23 September 2022",
                },
                {
                    id: 22,
                    foodImage: new URL("@/assets/blogImages/img--5.png", import.meta.url).href,
                    humanFace: new URL("@/assets/uiFaces/img_5.jpg", import.meta.url).href,
                    foodName: "Mac & Cheese",
                    desc: "Creamy pasta baked with cheddar cheese and breadcrumbs.",
                    name: "Isaac Cooper",
                    date: "30 September 2022",
                },
                {
                    id: 23,
                    foodImage: new URL("@/assets/blogImages/img--6.png", import.meta.url).href,
                    humanFace: new URL("@/assets/uiFaces/img_6.jpg", import.meta.url).href,
                    foodName: "Lentil Soup",
                    desc: "Hearty and healthy soup with lentils, carrots, and spices.",
                    name: "Olivia James",
                    date: "8 October 2022",
                },
                {
                    id: 24,
                    foodImage: new URL("@/assets/blogImages/img--1.png", import.meta.url).href,
                    humanFace: new URL("@/assets/uiFaces/img_1.jpg", import.meta.url).href,
                    foodName: "Fruit Parfait",
                    desc: "Layered yogurt, granola, and mixed berries in a glass.",
                    name: "Emma Watson",
                    date: "15 October 2022",
                },
            ]

        }
    },
    mutations,
    getters,
    actions,
}